# 服务监听与安全配置
server:
  addr: ":8080"
  # 应用基础路径（统一前缀）。默认为 /deployagent，可设为 "/" 或空表示根路径
  base_path: "/deployagent"
  secret: "CHANGE_ME_SECRET"
  upload_dir: "uploads"
  script_dir: "scripts"
  # 支持多个日志目录（相对于工作目录或绝对路径）。兼容旧字段 logs_dir
  logs_dirs:
    - "logs"
  # 允许的文件大小（字节），这里是 200MB
  max_upload_bytes: 209715200

# 简单的账户配置（无需数据库）
auth:
  users:
    - username: "admin"
      password: "admin123"  # 生产请更换


